### ISSUE TITLE
petit probleme

### ISSUE THREAD

**Issue by titof2375** [vingerha/pronote2mqtt#1]
bonjour, je ne comprent pas comment faire un docker compose pour pronote peu tu m'aider?

**Comment by vingerha** [comment]
J'assume que vous savez comment utilise docker?
Peut-être curieux mais..., je n'ais jamais (!) utlisé le docker compose.
Pour son installation j'utilise : 
```
docker run --name pronote2mqtt -v [dockerdir]/pronote2mqtt/app:/app -v [dockerdir]/pronote2mqtt:/data --tty vingerha/pronote2mqtt:latest
```
[dockerdir] est la base pour garder tout mes docker installations 'persistent'. 
Ensuite je gère tous avec portainer.

**Comment by titof2375** [comment]
docker@Docker:~$ docker run --name pronote2mqtt -v [dockerdir]/pronote2mqtt/app:/app -v [dockerdir]/pronote2mqtt:/data --tty vingerha/pronote2mqtt:latest
docker: Error response from daemon: create [dockerdir]/pronote2mqtt/app: "[dockerdir]/pronote2mqtt/app" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
docker@Docker:~$

**Comment by titof2375** [comment]
docker@Docker:~$ docker run --name pronote2mqtt -v [dockerdir]/pronote2mqtt/app:/app -v [dockerdir]/pronote2mqtt:/data --tty vingerha/pronote2mqtt:latest
docker: Error response from daemon: create [dockerdir]/pronote2mqtt/app: "[dockerdir]/pronote2mqtt/app" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
docker@Docker:~$

**Comment by titof2375** [comment]
docker@Docker:~$ docker run --name pronote2mqtt -v [dockerdir]/pronote2mqtt/app:/app -v [dockerdir]/pronote2mqtt:/data --tty vingerha/pronote2mqtt:latest
docker: Error response from daemon: create [dockerdir]/pronote2mqtt/app: "[dockerdir]/pronote2mqtt/app" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
docker@Docker:~$

**Comment by titof2375** [comment]
![pronote](https://user-images.githubusercontent.com/31250165/159178837-f5790f6e-31b1-4ce2-9df1-ba560dab01cb.PNG)
voila ce que j'ai
a tu telegram ou discord?

**Comment by vingerha** [comment]
If faut remplacer [docker] avec ton folder local, avec le folder local tu peut plus facillement connecter avec la based de données et les script python. Je suis sur discord sous le même nom ("HACF" ou "Domotique & DIY")

**Comment by vingerha** [comment]
closed...sol. ailleurs
